### ISSUE TITLE
如果倒數結束前關閉倒數畫面，不會顯示已領取

### ISSUE THREAD

**Issue by an22003937** [CPRTeam/CCIP-Android#1]
如果在倒數結束前就按 CLOSE 的話，他回到［快速通關］的頁面後，還是可以再點一次領取
那如果使用者已經領到餐了（或是領到小貓袋了），倒數還沒結束，使用者就把倒數畫面關閉的話，有可能導致重複領取（還是會倒數結束後才放人走？）

**Comment by TigerHuang** [comment]
倒數時間這邊會與場務組協調，看要調整為多少秒數。

**Comment by denny0223** [comment]
已與場務協調確認倒數時間
