### ISSUE TITLE
[question] 這個專案還會繼續維護嗎？

### ISSUE THREAD

**Issue by ALiangLiang** [CPRTeam/CCIP-Android#11]
如果有，那我幾個建議

**Comment by denny0223** [comment]
基本上會，如果有其他研討會考慮使用，非常樂意支援

**Comment by denny0223** [comment]
@ALiangLiang 目前已經確定該專案會於明年的 SITCON 學生計算機年會使用

非常歡迎將建議透過任何管道告訴我XD
