### ISSUE TITLE
Can't see countdown numbers in countdown pages

### ISSUE THREAD

**Issue by William-Tsai** [CPRTeam/CCIP-Android#4]
Tested on my HTC One M9 (Android 6.0) and HTC One M7 (Android 5.0.2), both didn't show countdown numbers in countdown pages. Only current time and close button is displayed. 
![image](https://cloud.githubusercontent.com/assets/14964983/17556052/8d778d8c-5f44-11e6-8aba-11a3acaccec2.png)
![image](https://cloud.githubusercontent.com/assets/14964983/17556068/99eb8726-5f44-11e6-81ec-f82922fab598.png)

**Comment by denny0223** [comment]
d9ce4d7d1485cc8c8e0c5fa6a3cec8171d34ec10 fix it, many devices not support textSize 250sp
