### ISSUE TITLE
時間倒數

### ISSUE THREAD

**Issue by yo-ga** [CPRTeam/CCIP-Android#5]
最後一秒到零秒時，明顯時間差較大
另外原本關閉前，中途離開倒數，仍可點擊其他選項，但重新開啟後，快速通關全都有綠色勾勾，除了義賣選項外，無法點擊。

**Comment by denny0223** [comment]
使用 CountDownTimer 實做 無法到非常精準

不過實際上也不用到如此精確，這樣的時間差還在可接受範圍


在倒數結束前都可以再次進入倒數畫面也能夠看到尚餘秒數 這是 feature

其他選項的時間設定會在活動當下做限制
