### ISSUE TITLE
Buttons doesn't render correctly after pressed "Checkin" button

### ISSUE THREAD

**Issue by William-Tsai** [CPRTeam/CCIP-Android#6]
After I pressed the "Day 1 Checkin" Button, Only "Day 1 Lunch" render as available, "Welcome Kit" is still greyed out. After "Day 2 Checkin" pressed, "Day 2 Lunch" is greyed out but "Special Gift" is marked with a check.
![image](https://cloud.githubusercontent.com/assets/14964983/17557200/d9fd6c7c-5f48-11e6-9754-a7f473b74d5e.png)
![image](https://cloud.githubusercontent.com/assets/14964983/17557211/e2971162-5f48-11e6-8cce-93478fc3b80a.png)

**Comment by denny0223** [comment]
Already fix it in ecd0a2fe740173bffc27250dae017ad5c7f01cee, and release on 0.7
