### ISSUE TITLE
「是否聽從工作人員指示」應該要寫得更清楚

### ISSUE THREAD

**Issue by rschiang** [CPRTeam/CCIP-Android#8]
如果點下去視同已經報到或是已經領便當的話，應該要出現警語才對。XD

（另外如果還沒到第二天，不應該允許第二天報到吧？）

**Comment by William-Tsai** [comment]
Maybe need a double check?

**Comment by denny0223** [comment]
大會當天 所以操作必須要在大會網路才可以運行

報到可以不用這麼嚴謹 領便當的話已經有 alert dialog 還是要再怎麼警告?

第二天還沒到不會允許第二天報到 目前測試階段所有的時間驗證是關閉的

**Comment by rschiang** [comment]
可能需要請場務組幫忙 review 一下？覺得「請確定已遵照工作人員指示」不夠清楚，~~出於好奇就會按下去了~~。owo)
