### ISSUE TITLE
Kit & VIP Kit 倒數畫面相同

### ISSUE THREAD

**Issue by TigerHuang** [CPRTeam/CCIP-Android#9]
Hi,

領取迎賓袋與個人贊助品的倒數頁面相同，無法讓工作人員識別

是否要參考領取午餐上方多個Text顯示領取的項目呢？

![screenshot_2016-08-11-11-19-52](https://cloud.githubusercontent.com/assets/1662405/17577940/ea2e4d10-5fb5-11e6-8b68-4122e683b28d.png)

**Comment by realever32** [comment]
個人贊助領取物品的位置不一樣，且需要核對身份，
所以顏色一樣不會構成問題。
